name: chatting_app_clone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  firebase_storage: ^11.1.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.5.1
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+3
  permission_handler_platform_interface: ^3.9.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Pretendard-Black
      fonts:
        - asset: assets/fonts/Pretendard-Black.otf
    - family: Pretendard-Bold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
    - family: Pretendard-ExtraBold
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.otf
    - family: Pretendard-ExtraLight
      fonts:
        - asset: assets/fonts/Pretendard-ExtraLight.otf
    - family: Pretendard-Light
      fonts:
        - asset: assets/fonts/Pretendard-Light.otf
    - family: Pretendard-Medium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf
    - family: Pretendard-Regular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
    - family: Pretendard-SemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.otf
    - family: Pretendard-Thin
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
